language: python
python:
  - "3.7"
  - "3.8"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install pytest
  - pip install pytest-mock
  - pip install pytest-cov
  - pip install pytest-recording
  - pip install coveralls
# command to run tests
script:
  - pytest --cov=bookops_worldcat/
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash ./travis/run_on_pull_requests; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./travis/run_on_non_pull_requests; fi'
after_success:
  - coveralls