language: python
python:
  - "3.7"
  - "3.8"
  - "3.9"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install pytest
  - pip install pytest-mock
  - pip install pytest-cov
  - pip install pytest-recording
  - pip install coveralls
# command to run tests
script:
  - pytest --cov=bookops_worldcat/
after_success:
  - coveralls
