site_name: BookOps-Worldcat Documentation
site_description: Documentation of BookOps-Worldcat library
nav:
  - Home: index.md
  - Changelog: changelog.md
  - Source Code: https://github.com/BookOps-CAT/bookops-worldcat
  - Issue Tracker: https://github.com/BookOps-CAT/bookops-worldcat/issues
  - Tutorials: tutorials.md
  - About: about.md
  - API: mkapi/api/bookops_worldcat
theme: readthedocs
plugins:
  - search
  - mkapi
  - mike:
      version_selector: true   # set to false to leave out the version selector
      css_dir: css             # the directory to put the version selector's CSS
      javascript_dir: js       # the directory to put the version selector's JS
      canonical_version: null  # the version for <link rel="canonical">; `null`
                               # uses the version specified via `mike deploy`
