site_name: BookOps-Worldcat Documentation
site_description: Documentation of BookOps-Worldcat library
site_url: https://bookops-cat.github.io/bookops-worldcat/
repo_name: bookops-worldcat
repo_url: https://github.com/BookOps-CAT/bookops-worldcat

theme:
  name: 'material'
  palette:
    scheme: NYPL
  features:
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.footer
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top

nav:
- BookOps-WorldCat:
  - Overview: index.md
  - Get Started: 
    - usage/index.md
    - Search WorldCat: usage/search.md
    - Manage Bibliographic Records: usage/manage_bibs.md
    - Manage Institution Holdings: usage/manage_holdings.md
    - Search and Manage Local Data: usage/local.md
    - Advanced Usage: usage/advanced.md
  - About:
    - about/index.md
    - Contributing: about/contributing.md
    - Changelog: about/changelog.md
    - Issue Tracker: https://github.com/BookOps-CAT/bookops-worldcat/issues
- API Documentation: mkapi/api/bookops_worldcat
- Tutorials: tutorials.md


markdown_extensions:
- admonition
- pymdownx.details
- pymdownx.superfences
- pymdownx.highlight:
    pygments_lang_class: true
- pymdownx.extra
- pymdownx.tabbed:
    alternate_style: true

watch:
- bookops_worldcat

plugins:
  - search
  - mkapi
  - mike:
      version_selector: true   # set to false to leave out the version selector
      css_dir: css             # the directory to put the version selector's CSS
      javascript_dir: js       # the directory to put the version selector's JS
      canonical_version: null  # the version for <link rel="canonical">; `null`
                               # uses the version specified via `mike deploy`
extra:
  version:
    provider: mike
extra_css:
  - stylesheets/extra.css