site_name: BookOps-Worldcat Documentation
site_description: Documentation of BookOps-Worldcat library
site_url: https://bookops-cat.github.io/bookops-worldcat/
repo_name: bookops-worldcat
repo_url: https://github.com/BookOps-CAT/bookops-worldcat

theme:
  name: 'material'
  palette:
    scheme: NYPL
  features:
    - content.tabs.link
    - content.code.copy
    - content.code.annotate
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.footer
    - navigation.sections
    - navigation.expand

nav:
- BookOps-WorldCat:
  - Overview: index.md
  - How To:
    - Get Started: start.md
    - Search WorldCat: search.md
    - Manage Bibliographic Records: manage_bibs.md
    - Manage Institution Holdings: manage_holdings.md
    - Search and Manage Local Data: local.md
    - Advanced Usage: advanced.md
  - About:
    - About BookOps: about.md
    - Contributing: contributing.md
    - Changelog: changelog.md
- API Documentation: 
    - bookops_worldcat:
      - bookops_worldcat.authorize: api/authorize.md
      - bookops_worldcat.errors: api/errors.md
      - bookops_worldcat.metadata_api: api/metadata_api.md
      - bookops_worldcat.query: api/query.md
      - bookops_worldcat.utils: api/utils.md
- Tutorials: tutorials.md


markdown_extensions:
- admonition
- pymdownx.details
- pymdownx.superfences
- pymdownx.highlight:
    pygments_lang_class: true
- pymdownx.extra
- pymdownx.tabbed:
    alternate_style: true
- tables
- md_in_html
- attr_list

watch:
- bookops_worldcat

plugins:
  - search
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true
            separate_signature: true
            filters: ["!^_"]
            docstring_options:
              ignore_init_summary: true
            docstring_section_style: spacy
            merge_init_into_class: true
            show_signature_annotations: true
          import:
            - https://docs.python.org/3/objects.inv
  - mike:
      version_selector: true   # set to false to leave out the version selector
      css_dir: css             # the directory to put the version selector's CSS
      javascript_dir: js       # the directory to put the version selector's JS
      canonical_version: null  # the version for <link rel="canonical">; `null`
                               # uses the version specified via `mike deploy`
extra:
  version:
    provider: mike
extra_css:
  - stylesheets/extra.css