[tool.poetry]
name = "bookops-worldcat"
version = "0.1.0"
description = "BookOps CAT OCLC APIs wrappers, in particular Search and Metadata APIs."
authors = ["Tomasz Kalata <klingaroo@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
requests = "^2.23"
requests-oauthlib = "^1.3"


[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
