name: live-tests
on: 
  pull_request:
    branches:
      - main
      - "releases/**"
  schedule: 
    - cron: '0 5 15 * *'
env:
  WCKey: ${{ secrets.WC_KEY }}
  WCSecret: ${{ secrets.WC_SECRET }}
  WCScopes: "WorldCatMetadataAPI"
jobs:
  webtests:
    name: Run live webtests
    if: ${{ github.event_name == 'schedule' || github.event_name == 'pull_request' && contains(fromJSON(vars.MAINTAINERS), github.actor) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install Poetry with pipx
        run: pipx install poetry          
      - name: Install dependencies
        run: poetry install --no-root --without docs
      - name: Run monthly live tests
        run: poetry run pytest -m "webtest"     