name: publish

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-release:
    name: Build distributions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install Poetry with pipx
        run: pipx install poetry

      - name: Install dependencies with poetry
        run: poetry install --no-root --without dev,docs
      
      - name: Build package distributions
        run: poetry build

      - name: Store the distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: bookops-worldcat-distributions
          path: dist/
          if-no-files-found: error

  publish-to-pypi:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    environment: 
      name: pypi
      url: https://pypi.org/project/bookops-worldcat    
    needs: build-release
    permissions:
      id-token: write
    steps:
      - name: Retrieve distributions
        uses: actions/download-artifact@v4
        with:
          name: bookops-worldcat-distributions
          path: dist/    
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1